name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - production
    paths:
      - 'Frontend/**'
      - '.github/workflows/deploy-frontend.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Create .env.production file
        run: |
          echo "VITE_GEMINI_URL=${{ secrets.VITE_GEMINI_URL_PROD }}" >> .env.production
          echo "VITE_APP_ENV=production" >> .env.production
        env:
          VITE_GEMINI_URL_PROD: ${{ secrets.VITE_GEMINI_URL_PROD }}

      - name: Build application
        run: npm run build

      - name: Create CNAME file
        run: echo "enpassant.wiki" > public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Frontend/dist
          cname: enpassant.wiki